apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
data:
  minio-password: {{ .Values.auth.password | b64enc | quote }}
